"""Orchestration layer (Step 6): Router/Planner -> single | sequential | parallel fan-out/fan-in -> Report Writer.

Nobody leaves empty-handed: whenever the company data cannot answer (no documents, SQL cannot help, agent failure) or the
question is simply a general one, the General Knowledge Agent answers from the Groq model's own knowledge, clearly labelled.
"""
from __future__ import annotations

import json
import re
import time
from concurrent.futures import ThreadPoolExecutor
from typing import Any, Dict, List, Optional

from . import config
from .agents import AGENT_SPECS, Agent, AgentResult, load_instructions
from .data_layer import DataStore, get_store
from .guardrails import check_user_input, sanitize_output
from .llm import LLMClient, LLMError
from .observability import Trace
from .rag import VectorIndex
from .tools import ToolBox

SPECIALISTS = ["trial_data_analyst", "literature_research", "ae_triage", "compound_similarity"]
SETUP_MSG = ("The Groq API key is missing. Create a free key at https://console.groq.com/keys, put it in the `.env` file as "
             "`GROQ_API_KEY=gsk_...`, then restart the app.")
GENERAL_BANNER = ("> **General knowledge answer** - this is *not* from PharmaSense company data%s. It was generated by the "
                  "Groq-hosted language model from its general knowledge, so please verify anything important.")
COMPANY_KW = re.compile(
    r"compound|\btrials?\b|trl-|cmp-|\bae-\d|adverse|\bsites?\b|\bassay|lab result|enrol|\bour\b|internal|memo|notebook|briefing|"
    r"sop deviation|dku-|[a-z]{3}-1\d{3}\b|pharmasense|escalat|portfolio|toxicity score|lead scientist|similar to", re.I)


def route_heuristic(q: str) -> Dict[str, Any]:
    """Keyword router used when the LLM router fails (and as a baseline in the evaluation)."""
    ql = q.lower()
    agents: List[str] = []
    if not COMPANY_KW.search(q):
        return {"intent": "general question", "pattern": "general", "agents": [], "sub_queries": {}}
    full_picture = bool(re.search(r"full picture|360|complete (profile|overview)|everything (we know|about)|dossier|report on", ql))
    if re.search(r"\bae-\d+|triage|serious adverse|adverse event.*(report|just|new)|\bsae\b", ql) and "how many" not in ql:
        return {"intent": "triage", "pattern": "single", "agents": ["ae_triage"], "sub_queries": {}}
    if full_picture:
        return {"intent": "compound_dossier", "pattern": "parallel",
                "agents": ["trial_data_analyst", "literature_research", "compound_similarity"], "sub_queries": {}}
    if re.search(r"similar|analog|nearest|like (compound|cmp|[a-z]{3}-\d{4})", ql):
        agents.append("compound_similarity")
    if re.search(r"research|literature|document|memo|notebook|briefing|abstract|sop|said about|findings|notes on", ql):
        agents.append("literature_research")
    data_kw = r"how many|average|mean|count|enrol|percent|%|pass rate|status|phase|trial|which (trials|compounds|countr)|top \d|most"
    if not agents or (re.search(data_kw, ql) and "similar" not in ql):
        if "trial_data_analyst" not in agents:
            agents.insert(0, "trial_data_analyst")
    pattern = "single" if len(agents) == 1 else "parallel"
    return {"intent": "heuristic", "pattern": pattern, "agents": agents[:4], "sub_queries": {}}


class PharmaSenseOrchestrator:
    def __init__(self, llm: Optional[LLMClient] = None, store: Optional[DataStore] = None):
        self.llm = llm or LLMClient()
        self.store = store or get_store()
        self.index = VectorIndex(self.store.table("research_documents"), self.store.table("compounds"))
        self.toolbox = ToolBox(self.store, self.index)
        self.agents = {k: Agent(spec, self.llm, self.toolbox, self.store) for k, spec in AGENT_SPECS.items()}
        self._router_prompt = load_instructions("router.md")

    # ------------------------------------------------------------------ router
    def plan(self, question: str, trace: Trace) -> Dict[str, Any]:
        name = config.AGENT_DISPLAY["router"]
        t0 = time.time()
        plan: Optional[Dict[str, Any]] = None
        err = None
        try:
            out = self.llm.call_llm([{"role": "system", "content": self._router_prompt},
                                     {"role": "user", "content": question}],
                                    config.MODEL_ROUTER, json_mode=True, temperature=0.0, max_tokens=1000, trace=trace, agent=name)
            m = re.search(r"\{.*\}", out.content or "", re.S)  # tolerate prose / code fences around the JSON
            plan = json.loads(m.group(0)) if m else None
            if isinstance(plan, dict):
                plan["router"] = "llm"
        except (LLMError, ValueError) as e:
            err = str(e)
            trace.add_event(name, "fallback", "heuristic_router", err[:200])
        if not isinstance(plan, dict):
            plan = route_heuristic(question)
            plan["router"] = "heuristic"
        plan = self._normalise(plan, question)
        trace.add_agent_run(name, int((time.time() - t0) * 1000), [], "Plan: %s -> %s" % (plan["pattern"], ", ".join(plan["agents"]) or "general"), False, err)
        return plan

    def _normalise(self, plan: Dict[str, Any], question: str) -> Dict[str, Any]:
        router = plan.get("router", "llm")
        if plan.get("pattern") in ("general", "out_of_scope"):
            return {"intent": str(plan.get("intent", "general question"))[:120], "pattern": "general", "agents": [],
                    "sub_queries": {}, "router": router}
        agents = [a for a in (plan.get("agents") or []) if a in SPECIALISTS]
        agents = list(dict.fromkeys(agents))[:4]
        if not agents:
            h = route_heuristic(question)
            if h["pattern"] == "general":
                return {"intent": "general question", "pattern": "general", "agents": [], "sub_queries": {}, "router": router}
            agents, plan["pattern"] = h["agents"], h["pattern"]
        pattern = plan.get("pattern") if plan.get("pattern") in ("single", "sequential", "parallel") else "single"
        if len(agents) > 1 and pattern == "single":
            pattern = "parallel"
        if len(agents) == 1 and pattern == "parallel":
            pattern = "single"
        sub = plan.get("sub_queries") if isinstance(plan.get("sub_queries"), dict) else {}
        sub = {k: str(v) for k, v in sub.items() if k in agents and isinstance(v, (str, int, float)) and str(v).strip()}
        return {"intent": str(plan.get("intent", ""))[:120], "pattern": pattern, "agents": agents, "sub_queries": sub, "router": router}

    # ------------------------------------------------------------------ main entry
    def ask(self, question: str, user_role: str = "Research Scientist", session_id: Optional[str] = None) -> Dict[str, Any]:
        trace = Trace(question, user_role, session_id)
        result: Dict[str, Any] = {"run_id": trace.run_id, "question": question, "answer": "", "refused": False,
                                  "refusal_reason": "", "plan": None, "agents": [], "sources": [], "escalations": [],
                                  "tool_events": [], "unverified_citations": [], "error": None, "answer_source": "company_data"}
        guard = check_user_input(question)
        if not guard.allowed:
            result.update(answer=guard.message, refused=True, refusal_reason=guard.reason, answer_source="refused")
            trace.add_event("Guardrails", "refusal", guard.reason, question[:200])
            trace.add_agent_run("Guardrails", 0, [], guard.message, False)
            return self._finish(result, trace)
        if not self.llm.available:
            result.update(answer=SETUP_MSG, error="missing_api_key", answer_source="error")
            return self._finish(result, trace)

        try:
            if guard.medical:  # personal-health question: answered in safe mode (general info, no personal dosing)
                plan = {"intent": "personal medical question (safe mode)", "pattern": "general", "agents": [], "sub_queries": {}, "router": "guardrail"}
            else:
                plan = self.plan(question, trace)
            result["plan"] = plan
            source = "company_data"

            if plan["pattern"] == "general":
                outs = [self._general(question, trace, medical=guard.medical)]
                final, source = outs[0].answer, "general_knowledge"
            elif plan["pattern"] == "single":
                first = self._run(plan["agents"][0], question, plan, trace)
                outs = [first]
                if first.no_evidence:
                    gen = self._general(question, trace, note=first.no_evidence_reason)
                    outs.append(gen)
                    final, source = gen.answer, "general_knowledge"
                else:
                    final = first.answer
            else:
                if plan["pattern"] == "sequential":
                    outs, ctx = [], ""
                    for key in plan["agents"]:
                        o = self._run(key, question, plan, trace, context=ctx)
                        outs.append(o)
                        ctx += "\n[%s]\n%s\n" % (o.name, o.answer)
                else:  # parallel fan-out / fan-in
                    with ThreadPoolExecutor(max_workers=config.MAX_PARALLEL_AGENTS) as pool:
                        futures = [pool.submit(self._run, k, question, plan, trace) for k in plan["agents"]]
                        outs = [f.result() for f in futures]
                gaps = [o for o in outs if o.no_evidence]
                if len(gaps) == len(outs):  # internal data had nothing at all -> general knowledge answers everything
                    gen = self._general(question, trace, note="; ".join(o.no_evidence_reason for o in gaps))
                    outs.append(gen)
                    final, source = gen.answer, "general_knowledge"
                else:
                    extras = []
                    for g in gaps[:2]:  # fill each gap with a labelled general-knowledge answer
                        sub = plan.get("sub_queries", {}).get(g.key) or question
                        extras.append((g, self._general(sub, trace, note=g.no_evidence_reason)))
                    outs.extend(e for _, e in extras)
                    final = self._write(question, outs, extras, trace)
                    source = "mixed" if gaps else "company_data"
            self._collect(result, outs, final)
            result["answer_source"] = source
            if source == "general_knowledge":
                reason = ""
                gaps_reason = [o.no_evidence_reason for o in outs if o.no_evidence]
                if gaps_reason:
                    reason = " (internal data check: %s)" % gaps_reason[0]
                result["answer"] = GENERAL_BANNER % reason + "\n\n" + result["answer"]
            elif source == "mixed":
                result["answer"] += "\n\n> Sections marked *General knowledge* are not from internal records."
        except LLMError as e:
            result["error"] = str(e)
            result["answer_source"] = "error"
            result["answer"] = "Sorry - the language model could not be reached: %s" % e
        return self._finish(result, trace)

    # ------------------------------------------------------------------ helpers
    def _run(self, key: str, question: str, plan: Dict[str, Any], trace: Trace, context: str = "") -> AgentResult:
        task = plan.get("sub_queries", {}).get(key) or question
        if task != question:
            task = "%s\n\n(Original user question: %s)" % (task, question)
        return self.agents[key].run(task, trace, context)

    def _general(self, question: str, trace: Trace, medical: bool = False, note: str = "") -> AgentResult:
        task = question
        if medical:
            task = "[MEDICAL SAFETY MODE]\n" + task
        if note:
            task += "\n\n(Internal PharmaSense data could not answer this: %s. Answer from general knowledge instead.)" % note
        return self.agents["general_knowledge"].run(task, trace)

    def _write(self, question: str, outs: List[AgentResult], extras, trace: Trace) -> str:
        gap_keys = {g.key: g for g, _ in extras}
        parts = []
        for o in outs:
            if o.key == "general_knowledge":
                continue
            if o.no_evidence:
                parts.append("### %s\n(no internal data found: %s)" % (o.name, o.no_evidence_reason))
            else:
                parts.append("### %s\n%s" % (o.name, o.answer[:2500]))
        for g, gen in extras:
            parts.append("### General Knowledge Agent (NOT internal data; covers the gap of %s)\n%s" % (g.name, gen.answer[:2000]))
        task = "User question: %s\n\nAGENT OUTPUTS TO MERGE:\n\n%s" % (question, "\n\n".join(parts))
        res = self.agents["report_writer"].run(task, trace)
        if res.error or not res.answer.strip():  # never return empty: fall back to a plain concatenation
            return "\n\n".join(p for p in parts)
        return res.answer

    def _collect(self, result: Dict[str, Any], outs: List[AgentResult], final: str) -> None:
        known: List[str] = []
        for o in outs:
            for d in o.doc_ids:
                if d not in known:
                    known.append(d)
            result["escalations"].extend(o.escalations)
            result["tool_events"].extend(o.tool_events)
            result["agents"].append({"key": o.key, "name": o.name, "answer": o.answer, "tools_used": o.tools_used,
                                     "latency_ms": o.latency_ms, "error": o.error, "doc_ids": o.doc_ids,
                                     "no_evidence": o.no_evidence})
        cited = list(dict.fromkeys(re.findall(r"DOC-\d{5}", final)))
        result["unverified_citations"] = [d for d in cited if d not in known and d not in
                                          set(self.store.table("research_documents")["doc_id"])]
        use = [d for d in cited if d in known] or known[:5]
        if use:
            cites = self.toolbox.citation_formatter_tool(use)["citations"]
            result["sources"] = cites
            final = final + "\n\n**Sources**\n" + "\n".join("- " + c for c in cites)
        result["answer"] = final

    def _finish(self, result: Dict[str, Any], trace: Trace) -> Dict[str, Any]:
        if not (result["answer"] or "").strip():  # last line of defence: never return an empty reply
            result["answer"] = "I couldn't produce an answer this time. Please rephrase the question or try again."
        result["answer"] = sanitize_output(result["answer"])
        result["metrics"] = trace.totals()
        result["trace_events"] = trace.events
        result["agent_runs"] = trace.agent_runs
        try:
            trace.flush()
        except OSError:
            pass
        return result
